service: controversy-cards

plugins:
  - serverless-webpack
  - serverless-secrets-plugin

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev

functions:
  metacardsList:
    handler: cards.get
    description: Gets a complete listing of the controversy card collection
    environment:
      MLABDB: ${self:custom.secrets.MLABDB}
    events:
      - http:
          path: cards/{id}
          method: get
          cors: true
          integration: lambda

# enable auto-packing of external modules
custom:
  webpackIncludeModules: true
  secrets: ${file(secrets.${opt:stage, self:provider.stage}.yml)}
